### PR TITLE
Add temperature support

### PR DESCRIPTION
**Pull request by Ninic0c0**
First try to add temperature support.

Please double check formula :)

### CODE REVIEW

**Comment by ladyada** [comment]
@dherrada wanna review this PR? :)

**Review by dhalbert — APPROVED** [review]
I reformatted with black, and also tested a real sensor. Seems to work fine. I did not test below-zero temperatures, or similar boundary cases.

**Comment by jposada202020** [comment]
@dhalbert maybe correct this line :) https://github.com/adafruit/Adafruit_CircuitPython_LSM6DS/blob/9c03539e85b9a8773fbc62967b8d3b9b69d4b090/adafruit_lsm6ds/__init__.py#L167. do not want to step in your toes, trying to be helpful :)

**Comment by dhalbert** [comment]
> @dhalbert maybe correct this line :)
> 
> https://github.com/adafruit/Adafruit_CircuitPython_LSM6DS/blob/9c03539e85b9a8773fbc62967b8d3b9b69d4b090/adafruit_lsm6ds/__init__.py#L167
> 
> . do not want to step in your toes, trying to be helpful :)

Good point!

**Pull request merged**
